### ISSUE TITLE
Package JSON and LICENSE.md disagree

### ISSUE THREAD

**Issue by poelstra** [jslicense/spdx-ranges.js#2]
Thanks for your SPDX packages! They are very useful!

I noticed that your LICENSE.md file indicates `MIT`, whereas your package.json says `CC-BY-3.0`.
Can you please clarify?

**Comment by poelstra** [comment]
Wow, that's fast, thanks! :+1:

**Comment by kemitchell** [comment]
@poelstra Mind me asking how you're using the package?

**Comment by poelstra** [comment]
Sure: we're building a tool to verify all licenses of all used projects. For this, I'm using `spdx-whitelisted`, which uses this package.

And our license checker is a part of the projects themselves, which means it was checking the licenses of its own dependencies as well :)
